[package]
name = "rubedo"
version = "0.1.1"
description = "Library of useful functionality and extensions"
categories = []
keywords = ["library", "utility"]
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["alloc", "clock", "std"] }
futures = "0.3.28"
hyper = "0.14.27"
