[package]
name = "rubedo"
version = "0.3.6"
description = "Library of useful functionality and extensions"
categories = []
keywords = ["library", "utility"]
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
reasons = []

[dependencies]
base64 = "0.21.4"
chrono = { version = "0.4.31", features = ["alloc", "clock", "std"] }
futures = "0.3.28"
http = "0.2.9"
http-body = "0.4.5"
hyper = "0.14.27"
rubedo-macros = { path = "../rubedo-macros", version = "0.3.6" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.107", features = ["preserve_order"] }

[dev-dependencies]
assert-json-diff = "2.0.2"
axum = "0.6.20"
claims = "0.7.1"
serde_assert = "0.5.0"
