[package]
name = "rubedo-macros"
version = "0.1.0"
description = "Proc macros for Rubedo"
categories = []
keywords = ["macro", "library", "utility"]

authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"

[dev-dependencies]
trybuild = "1.0.85"
